docker: fix pacman-keyring auto update issue.
While updateing the pacman-keyring package, such error orccues:

error: key "6D42BDD116E0068F" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)

The packaing cannot update itself, we need to install it with the
pacman -U option from the cache.